# Generated by Django 2.1 on 2019-06-15 17:35

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classify', models.CharField(choices=[('announcement', '网站公告'), ('industry_information', '行业资讯'), ('media_report', '媒体报道')], max_length=36, verbose_name='文章分类')),
                ('image', models.ImageField(max_length=200, upload_to='new/%Y/%m', verbose_name='封面')),
                ('title', models.CharField(max_length=64, verbose_name='文章标题')),
                ('author', models.CharField(default='YuKalix', max_length=32, verbose_name='文章作者')),
                ('intro', models.CharField(default='', max_length=300, verbose_name='文章简介')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='文章内容')),
                ('read_num', models.PositiveIntegerField(default=0, verbose_name='文章数量')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶(首页)')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否展示')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
    ]
