# Generated by Django 2.1 on 2019-06-13 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classify', models.CharField(choices=[('announcement', '网站公告'), ('industry_information', '行业资讯'), ('media_report', '媒体报道')], max_length=36, verbose_name='文章分类')),
                ('image', models.ImageField(max_length=200, upload_to='new/%Y/%m')),
                ('title', models.CharField(max_length=64, verbose_name='文章标题')),
                ('author', models.CharField(default='YuKalix', max_length=32, verbose_name='文章作者')),
                ('intro', models.CharField(default='', max_length=300, verbose_name='文章简介')),
                ('content', models.TextField(default='', verbose_name='文章内容')),
                ('read_num', models.PositiveIntegerField(default=0, verbose_name='文章数量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
    ]
