# Generated by Django 2.1 on 2019-06-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(max_length=200, upload_to='new/%Y/%m', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='new',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='是否展示'),
        ),
    ]
