# Generated by Django 2.1 on 2019-06-14 10:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_auto_20190613_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=ckeditor.fields.RichTextField(default='', verbose_name='文章内容'),
        ),
    ]
