# Generated by Django 2.1 on 2019-06-14 10:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_auto_20190614_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='文章内容'),
        ),
    ]
