# Generated by Django 2.1 on 2019-06-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0004_auto_20190614_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='is_top',
            field=models.BooleanField(default=True, verbose_name='是否置顶(首页)'),
        ),
    ]
