# Generated by Django 2.1 on 2019-06-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0005_new_is_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='是否置顶(首页)'),
        ),
    ]
