# Generated by Django 2.1 on 2019-06-15 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='banner/%Y')),
                ('describe', models.CharField(max_length=50, verbose_name='banner描述')),
                ('url', models.URLField(verbose_name='banner链接')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '首页banner',
                'verbose_name_plural': '首页banner',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='星之羽网络科技有限公司', max_length=36, verbose_name='企业名称')),
                ('introduce', models.TextField(blank=True, default='', max_length=360, verbose_name='企业描述')),
                ('address', models.CharField(blank=True, default='', max_length=72, verbose_name='企业地址')),
                ('mobile', models.CharField(blank=True, default='', max_length=12, verbose_name='企业电话')),
                ('qq', models.CharField(blank=True, default='', max_length=12, verbose_name='企业QQ')),
                ('email', models.EmailField(blank=True, default='admin@admin.admin', max_length=254, verbose_name='企业邮箱')),
                ('icp', models.CharField(blank=True, default='', max_length=100, verbose_name='企业备案号')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否使用')),
            ],
            options={
                'verbose_name': '企业信息',
                'verbose_name_plural': '企业信息',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='logo/%Y')),
                ('describe', models.CharField(max_length=50, verbose_name='logo描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '首页logo',
                'verbose_name_plural': '首页logo',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='partner/%Y')),
                ('name', models.CharField(max_length=16, verbose_name='企业名称')),
                ('introduce', models.TextField(max_length=160, verbose_name='介绍')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否合作')),
            ],
            options={
                'verbose_name': '合作伙伴',
                'verbose_name_plural': '合作伙伴',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='service/%Y')),
                ('describe', models.CharField(max_length=50, verbose_name='service描述')),
                ('url', models.CharField(default='#serve', max_length=100, verbose_name='service链接')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否使用')),
            ],
            options={
                'verbose_name': '我们的服务',
                'verbose_name_plural': '我们的服务',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(max_length=200, upload_to='team/%Y')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('introduce', models.TextField(max_length=160, verbose_name='介绍')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否在职')),
            ],
            options={
                'verbose_name': '我们的团队',
                'verbose_name_plural': '我们的团队',
            },
        ),
    ]
