# Generated by Django 2.1 on 2019-06-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20190611_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='address',
            field=models.CharField(blank=True, default='', max_length=72, verbose_name='企业地址'),
        ),
        migrations.AlterField(
            model_name='information',
            name='email',
            field=models.EmailField(blank=True, default='admin@admin.admin', max_length=254, verbose_name='企业邮箱'),
        ),
        migrations.AlterField(
            model_name='information',
            name='icp',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='企业备案号'),
        ),
        migrations.AlterField(
            model_name='information',
            name='introduce',
            field=models.CharField(blank=True, default='', max_length=360, verbose_name='企业描述'),
        ),
        migrations.AlterField(
            model_name='information',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='企业电话'),
        ),
        migrations.AlterField(
            model_name='information',
            name='name',
            field=models.CharField(blank=True, default='星之羽网络科技有限公司', max_length=36, verbose_name='企业名称'),
        ),
        migrations.AlterField(
            model_name='information',
            name='qq',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='企业QQ'),
        ),
    ]
