# Generated by Django 2.1 on 2019-06-11 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190611_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='information',
            name='is_delete',
            field=models.BooleanField(default=1, verbose_name='是否删除'),
            preserve_default=False,
        ),
    ]
