# Generated by Django 2.1 on 2019-06-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20190611_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='introduce',
            field=models.TextField(blank=True, default='', max_length=360, verbose_name='企业描述'),
        ),
        migrations.AlterField(
            model_name='information',
            name='is_delete',
            field=models.BooleanField(verbose_name='是否使用'),
        ),
    ]
