# Generated by Django 2.1 on 2019-06-11 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20190611_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='service/%Y')),
                ('describe', models.CharField(max_length=50, verbose_name='service描述')),
                ('url', models.URLField(default='#', verbose_name='service链接')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '我们的服务',
                'verbose_name_plural': '我们的服务',
            },
        ),
    ]
