# Generated by Django 2.1 on 2019-06-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_delete',
            field=models.BooleanField(default=1, verbose_name='是否使用'),
            preserve_default=False,
        ),
    ]
