# Generated by Django 2.1 on 2019-06-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_service_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='url',
            field=models.URLField(default='', verbose_name='service链接'),
        ),
    ]
