# Generated by Django 2.1 on 2019-06-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20190611_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='url',
            field=models.CharField(default='#serve', max_length=100, verbose_name='service链接'),
        ),
    ]
